# Dependencies
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Dharma Wheel
tagline:          'A Dharma blog, with instant search'
description:      'A Dharma blog, with instant search'
url:              https://github.com/lithienanh/hyde
baseurl:
# Travis will install Bundler dependencies in ./vendor, so we need to exclude it
# otherwise Jekyll will try to build it (and fail)
exclude:          [vendor]

author:
  name:           'lithienanh'
  url:            https://github.com/lithienanh

paginate:         5

# Custom vars
version:          1.0.0

github:
    repo:         https://github.com/lithienanh/hyde

# Algolia
gems:
  - algoliasearch-jekyll

algolia:
  application_id: 'ANBV9I9CZT'
  index_name: 'jekyll'
  read_only_api_key: 'a4db0110e49a575127fc18dc4396739e'
  excluded_files:
    - 404.html
    - index.html
